### ISSUE TITLE
Convert the SQL Tables to JSON file

### ISSUE THREAD

**Issue by sombek** [usefksa/Saudi_GIS_Data#2]
Hi @usefksa @daif 

- I would like to convert the SQL Tables to one JSON file.
- Add English translation for each one.
- I think there is an issue with sa_regions.sql I can't preview it on github. 

Let me know if you are interested.
Then I will start to build it, and PR it.

**Comment by usefksa** [comment]
Hi,
Please make a pull request if you created a json file for any database system. The current SQL file is valid for MySQL. I'm not sure if you can use it for other SQL server or not. 
The file sa_regions.sql is too large, you need to download on your machine.

We will be happy if you share any contents :)
Thanks
